layout_spectrum: 0
typography_spectrum: 0.8340425
color:
  saturation: 0.9500025
  lightness: 0.8482252
  brandStrength: 0.02856653
  rhythmicContrast: 0.6915814
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: BleepTwig
